spring :
  datasource :
    url :
      jdbc:postgresql://localhost:5433/recipe_db
    username : postgres
    password : root
  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true
server :
  port : 8081

springdoc :
  api-docs :
    path : /api-docs
  swagger-ui :
    path : /swagger-ui.html
info :
  title : Recipe API
  version : 1.0
  description : API for managing food recipes
  contact :
      name : Snehalata Raut
      email : snehalataraut@outlook.com
servers :
  url : http://localhost:8081
  description : Development








