{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8081",
      "description": "Generated server url"
    }
  ],
  "tags": [
    {
      "name": "RecipeController",
      "description": "API for managing recipes: create, update, delete, retrieve and search."
    }
  ],
  "paths": {
    "/api/v1/recipes/{id}": {
      "get": {
        "tags": [
          "RecipeController"
        ],
        "summary": "Retrieve a recipe by ID",
        "description": "Fetches a single recipe by its unique ID.",
        "operationId": "getRecipeById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Retrieve recipe based on ID.",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "ID is null",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipesResponse"
                }
              }
            }
          },
          "404": {
            "description": "Entity Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "RecipeController"
        ],
        "summary": "Update a recipe by ID",
        "description": "Updates an existing recipe identified by its ID and returns the updated recipe.",
        "operationId": "updateRecipe",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of Recipe to update",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RecipeRequestDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "404": {
            "description": "Recipe not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipesResponse"
                }
              }
            }
          },
          "400": {
            "description": "Input ID or entity to update is Invalid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "RecipeController"
        ],
        "summary": "Delete a recipe by ID",
        "description": "Deletes the recipe with the specified ID.",
        "operationId": "deleteRecipe",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID to delete Recipe",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Recipe deleted successfully"
          },
          "400": {
            "description": "ID is invalid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "ID not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/recipes": {
      "get": {
        "tags": [
          "RecipeController"
        ],
        "summary": "Retrieve all recipes",
        "description": "Fetches a list of all available recipes.",
        "operationId": "getAllRecipes",
        "responses": {
          "400": {
            "description": "Invalid request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RecipesResponse"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "RecipeController"
        ],
        "summary": "Create a new recipe",
        "description": "Creates a new recipe with the given details and returns the created recipe.",
        "operationId": "createRecipe",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RecipeRequestDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "404": {
            "description": "Recipe not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "201": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipesResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/recipes/search": {
      "get": {
        "tags": [
          "RecipeController"
        ],
        "summary": "Search recipes with filters",
        "description": "Filters recipes based on vegetarian preference, number of servings, ingredients to include/exclude, and instruction text.",
        "operationId": "searchRecipes",
        "parameters": [
          {
            "name": "isVegetarian",
            "in": "query",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "servings",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "includeIngredients",
            "in": "query",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "style": "form",
            "explode": true
          },
          {
            "name": "excludeIngredients",
            "in": "query",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "style": "form",
            "explode": true
          },
          {
            "name": "instructionText",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RecipesResponse"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RecipeRequestDto": {
        "required": [
          "ingredients",
          "instructions",
          "recipeName",
          "servings",
          "isVegetarian"
        ],
        "type": "object",
        "properties": {
          "recipeName": {
            "type": "string",
            "minLength": 1
          },
          "isVegetarian": {
            "type": "boolean"
          },
          "servings": {
            "minimum": 1,
            "type": "integer",
            "format": "int32"
          },
          "ingredients": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "instructions": {
            "type": "string",
            "minItems": 1
          }
        },
        "description": "New Recipe to create."
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "statusCode": {
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "RecipesResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "isVegetarian": {
            "type": "boolean"
          },
          "servings": {
            "type": "integer",
            "format": "int32"
          },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "instructions": {
            "type": "string"
          }
        }
      }
    }
  }
}